# Generated by Django 4.0.2 on 2022-02-12 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deliveryDate', models.DateField(default=django.utils.timezone.now)),
                ('creationDate', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('estimatedTime', models.IntegerField(default=1)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=0)),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GestionnaireProjet.project')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionnaireProjet.projectmanager')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionnaireProjet.projectmanager'),
        ),
    ]
